#!/bin/bash

# Description: This script extracts various archive file formats based on their extension.
# Dependency: zip, tar, 7z, xz, gzip

# Prints an help message 
if [[ "$1" == "-h" || "$1" == "--help" ]]; then
    echo "This script extracts various archive file formats based on their extension."
    echo "Usage: "
    echo "      extract [filename] "
    echo "Example: "
    echo "      extract documents.zip"
    exit 0
fi

# Check if tar is installed
if ! command -v tar >/dev/null 2>&1; then
  echo "Error: 'tar' is not installed. Please install it using your package manager."
  exit 1
fi

# Check if 7z is installed
if ! command -v 7z >/dev/null 2>&1; then
  echo "Error: 'p7zip' is not installed. Please install it using your package manager."
  exit 1
fi

# Check if xz is installed
if ! command -v xz >/dev/null 2>&1; then
  echo "Error: 'xz' is not installed. Please install it using your package manager."
  exit 1
fi

# Check if a file is provided
if [ -z "$1" ]; then
  echo "Error: Please provide a file to extract."
  exit 1
fi

# checks if the file exist
if [ ! -f "$1" ]; then
    echo "File does not exist."
    exit 1
fi


# Extract the file based on its extension
filename=$(echo "$1")
case "$filename" in
  *.zip)
    unzip "$filename"
    ;;
  *.tar)
    tar xvf "$filename"
    ;;
  *.tar.gz | tgz)
    tar xzvf "$filename"
    ;;
  *.tar.bz2)
    tar xjvf "$filename"
    ;;
  *.tar.xz | txz)
    tar Jxvf "$filename"
    ;;
  *.tar.lzma | taz)
    tar --lzma -xvf "$filename"
    ;;
  *.tar.Z)
    tar Zxvf "$filename"
    ;;
  *.tar.lzo)
    tar --lzop -xvf "$filename"
    ;;
  *.tar.lz)
    tar --lzip -xvf "$filename"
    ;;
  *.tar.lrz)
    tar --lrzip -xvf "$filename"
    ;;
  *.7z)
    7z x "$filename"
    ;;
  *.gz)
    gzip -dv "$filename"
    ;;
  *.xz)
    xz -dv "$filename"
    ;;
  *)
    echo "Error: Unsupported file extension."
    exit 1
    ;;
esac

# checks the extraction completed without any errors
if [[ $? == 0 ]]; then
  echo "Extraction completed!"
  exit 0
else
  echo "Extraction failed!"
  exit 1
fi